# Generated by Django 4.1.3 on 2022-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=155)),
                ('album', models.CharField(max_length=155)),
                ('img', models.ImageField(blank=True, null=True, upload_to='content')),
                ('genre', models.CharField(choices=[('RM', 'Roman'), ('RP', 'Rap'), ('RC', 'Rock'), ('CL', 'Classic'), ('SC', 'Sience'), ('FN', 'Funny'), ('FT', 'Fantasy'), ('ET', 'Entertainment'), ('PP', 'Pop'), ('JZ', 'Jazz')], max_length=2)),
                ('content', models.TextField()),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
