# Generated by Django 4.1.3 on 2022-11-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterField(
            model_name='content',
            name='album',
            field=models.CharField(max_length=155, verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(max_length=155, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('RM', 'Roman'), ('RP', 'Rap'), ('RC', 'Rock'), ('CL', 'Classic'), ('SC', 'Sience'), ('FN', 'Funny'), ('FT', 'Fantasy'), ('ET', 'Entertainment'), ('PP', 'Pop'), ('JZ', 'Jazz')], max_length=2, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='content',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='content', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='content',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes_no', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='content.content')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
