# Generated by Django 4.1.3 on 2022-11-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_options_alter_content_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.FileField(upload_to='file', verbose_name='Контент'),
        ),
    ]
