# Generated by Django 4.1.3 on 2022-11-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_content_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('Roman', 'Roman'), ('Rap', 'Rap'), ('Rock', 'Rock'), ('Classic', 'Classic'), ('Sience', 'Sience'), ('Funny', 'Funny'), ('Fantasy', 'Fantasy'), ('Entertainment', 'Entertainment'), ('Pop', 'Pop'), ('Jazz', 'Jazz')], max_length=15, verbose_name='Жанр'),
        ),
    ]
