# Generated by Django 4.1.3 on 2022-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='male',
            field=models.CharField(blank=True, choices=[('ML', 'MALE'), ('FM', 'FEMALE')], max_length=2, null=True),
        ),
    ]
