# Generated by Django 4.1.3 on 2022-11-07 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_alter_user_age_alter_user_male'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
